defaults:
  - model: global
  - loss: contrastive
  - generator: biggan
  - projector: identity
  - hparams: default # change when Hydra 1.1 releases
  - misc: train_misc
  - size: ${defaults.2.generator}_${defaults.3.projector} # change when Hydra 1.1 releases
  - hydra/job_logging: custom
  - hydra/output: custom